// Javascript/React/Advanced-React-Redux-2018-Edition/AdvancedReduxCode/testing/src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route } from 'react-router-dom';
import Root from 'Root';
import App from 'components/App';

ReactDOM.render(
  <Root>
    <BrowserRouter>
      <Route path="/" component={App} />
    </BrowserRouter>
  </Root>,
  document.querySelector('#root')
);

// Javascript/Angular-reactjs-vuejs-quickstart-comparison/Vue.js/Vue Cli/vue-framework-intro/src/main.js
import Vue from 'vue'
import VueRouter from 'vue-router';
import App from './App.vue'
import User from './components/User.vue';
import Blog from './components/Blog.vue';
import Account from './components/Account.vue';

Vue.use(VueRouter);

const routes = [
	{ path: '/blog', component: Blog },
	{ path: '/account', component: Account },
	{ path: '/', component: User },
];

const router = new VueRouter({
	routes,
	mode: 'history'
});

Vue.component('app-user', User);

new Vue({
  el: '#app',
  router,
  render: h => h(App)
})
